<?php
$xmlstr = <<<XML
<?xml version='1.0' standalone='yes'?>
<titelseite>
 <headline>
    <de>Ausstattungen und Preise</de>
    <fr>Equipements et prix</fr>
    <it>Equipaggiamenti e prezzi</it>
 </headline>
 <monate>
    <monat>
        <de>Januar</de>
        <fr>Janvier</fr>
        <it>Gennaio</it>
    </monat>
    <monat>
        <de>Februar</de>
        <fr>Février</fr>
        <it>Febbraio</it>
    </monat>
    <monat>
        <de>März</de>
        <fr>Mars</fr>
        <it>Marzo</it>
    </monat>
    <monat>
        <de>April</de>
        <fr>Avril</fr>
        <it>Aprile</it>
    </monat>
    <monat>
        <de>Mai</de>
        <fr>Mai</fr>
        <it>Maggio</it>
    </monat>
    <monat>
        <de>Juni</de>
        <fr>Juin</fr>
        <it>Giugno</it>
    </monat>
    <monat>
        <de>Juli</de>
        <fr>Juillet</fr>
        <it>Luglio</it>
    </monat>
    <monat>
        <de>August</de>
        <fr>Août</fr>
        <it>Agosto</it>
    </monat>
    <monat>
        <de>September</de>
        <fr>Aeptembre</fr>
        <it>Settembre</it>
    </monat>
    <monat>
        <de>Oktober</de>
        <fr>Octobre</fr>
        <it>Ottobre</it>
    </monat>
    <monat>
        <de>November</de>
        <fr>Novembre</fr>
        <it>Novembre</it>
    </monat>
    <monat>
        <de>Dezember</de>
        <fr>Décembre</fr>
        <it>Dicembre</it>
    </monat>
 </monate>
</titelseite>
XML;
?>